name: BroadwaterScenic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e2dbd2'
    - '#66615d'
    - '#e2a45f'
    - '#9f1f1a'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
