name: BroadwaterScenic
favicon: null
layout_spectrum: 0.68915
typography_spectrum: 0.34182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#81413e'
    - '#9f5e5c'
    - '#cd9295'
    - '#ebbbba'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
