name: BroadwaterScenic
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56174
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e4245'
    - '#f1f1f3'
    - '#8d8e89'
    - '#c79f7b'
    - '#bfc3dc'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
